function replaceText(){if(!document.getElementById){return;}
bodyText = document.getElementById("comments");
theText = bodyText.innerHTML;
theText = theText.replace(/\/\=r/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/icon-cuoi-khinh-hungvb.png'/>");
theText = theText.replace(/:\)\)/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/cuoi-chay-mo-hoi-hungvb.png'/>");
theText = theText.replace(/;\)/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/nhay-mat-emoji-hungvb.png'/>");
theText = theText.replace(/=\)\)/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/cuoi-ra-nuoc-mat-hungvb.png'/>");
theText = theText.replace(/:\(\(/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/khoc-cmnr-hungvb.png'/>");
theText = theText.replace(/&lt;3/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/heart-em-hungvb.png'/>");
theText = theText.replace(/:v/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/pac-man-emoji-hungvb.png'/>");
theText = theText.replace(/:\)/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/cuoi-mim-emoji-hungvb.png'/>");
theText = theText.replace(/:\(/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/sad-emoji-hungvb.png'/>");
theText = theText.replace(/==/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/emoji-mat-hungvb.png''/>");
theText = theText.replace(/:\*/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/kiss-hungvb.png'/>");
theText = theText.replace(/:D/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/cuoi-nhe-rang-hungvb.png'/>");
theText = theText.replace(/\^\_\^/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/cuoi-thoa-man-hungvb.png'/>");
theText = theText.replace(/\/=s/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/cuc-shit-hungvb.png'/>");
theText = theText.replace(/\/=ok/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/ok-hungvb.png'/>");
theText = theText.replace(/\/=hi/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/hi-hungvb.png'/>");
theText = theText.replace(/\(y\)/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/like-hungvb.png'/>");
theText = theText.replace(/:p/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/hahe-hungvb.png'/>");
theText = theText.replace(/\(yy\)/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/dislike-hungvb.png'/>");
theText = theText.replace(/\/=l/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/liec-cmn-mat-hungvb.png'/>");
theText = theText.replace(/\:\-\)/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/haiz-hungvb.png'/>");
theText = theText.replace(/\/=hl/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/hand-left-hungvb.png'/>");
theText = theText.replace(/\/=hr/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/hand-right-hungvb.png'/>");
theText = theText.replace(/\/=hup/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/hand-up-hungvb.png'/>");
theText = theText.replace(/\/=hd/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/hand-down-hungvb.png'/>");
theText = theText.replace(/\/=j/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/hand-down-hungvb.png'/>");
theText = theText.replace(/\/=clap/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/clap-hand-hungvb-Com.png'/>");
theText = theText.replace(/\/=he/gi, "<img class='bacsiwindows_emoticon' src='https://cdn.jsdelivr.net/gh/hungvb/bieu-tuong/love-hungvb.png'/>");
bodyText.innerHTML = theText;
}replaceText();